site_name: CakeFS 
site_url: https://cakeio-unreal.github.io
theme:
  name: material
  logo: assets/DocIcon256.png
  font:
    text: Onest
    code: Fira Code
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black 

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.tooltips

plugins:
  - macros
  - table-reader

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.superfences 
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details  
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path: "docs/.snippets/"
      auto_append:
        - abbreviations.md
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Tour: tour.md
  - Getting Started:
    - Installation: getting-started/installation.md
  - Core API Documentation: 
    - Overview: core-api/overview.md 
    - Core Objects:
      - Paths: core-api/paths.md
      - File Extensions: core-api/file-extensions.md
      - Files: core-api/files.md
      - Directories: core-api/directories.md
    - Error Handling:
      - Error Handling Patterns: core-api/error-handling.md
      - Error Maps: core-api/error-maps.md
    - Special Types:
      - Policies: core-api/special-types/policies.md
      - Outcomes: core-api/special-types/outcomes.md
      - Signals: core-api/special-types/signals.md
      - Results: core-api/special-types/results.md
      - Cake Orders: core-api/special-types/cake-orders.md
      - Settings: core-api/special-types/settings.md
    - Advanced Usage: 
      - Overview: core-api/advanced-usage.md
      - Utility Libraries:
        - CakeMix: core-api/cake-mix.md
        - CakeAsyncFS: core-api/cake-async-fs.md
      - CakeFS Services:
        - CakeFS Services Overview: core-api/services.md
  - Examples: 
    - Overview: examples/examples.md
    - Basic:
      - Discovering Unreal Modules: examples/basic/discovering_unreal_modules.md

  - Future Development: future-dev/future-development.md
watch:
  - tables

  
