site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Inter
    code: Fira Code
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - content.tooltips

plugins:
  - macros
  - table-reader

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.superfences 
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details  
  - abbr
  - attr_list
  - pymdownx.snippets:
      base_path: "docs/.snippets/"
      auto_append:
        - abbreviations.md
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Core API: 
    - API Overview: core-api/api-overview.md

    - Core Objects:
      - Paths: core-api/paths.md
      - File Extensions: core-api/file-extensions.md
      - Files: core-api/files.md
      - Directories: core-api/directories.md
    - Special Types:
      - Policies: core-api/special-types/policies.md
      - Outcomes: core-api/special-types/outcomes.md
      - Signals: core-api/special-types/signals.md
      - Results: core-api/special-types/results.md
      - Orders: core-api/special-types/orders.md
      - Settings: core-api/special-types/settings.md
      - Cake Ext Filter: core-api/special-types/cakeextfilter.md
    - Error Handling:
      - Error Handling Patterns: core-api/error-handling.md
  - Advanced: 
    - Advanced Cake IO: advanced/index.md
    - Cake Mix Library: advanced/cake-mix-library.md
    - Advanced Error Types: advanced/advanced-error-types.md
    - Advanced Error Handling: advanced/advanced-error-handling.md
    - Async IO: advanced/async-io.md
    - Low Level Services: advanced/services.md
  - Miscellanous:
    - FStringView: misc/stringview.md
    - CakeIO and C++ 20: misc/cpp20-features.md
    - CakeIO and Lifetimes: misc/lifetimes.md
watch:
  - tables
  - img

  
